version: '3.9'

services:
  db:
    image: postgres
    container_name: book_container
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
      POSTGRES_DB: book
    ports:
      - "5432:5432"
    volumes:
      - book_pgdata:/var/lib/postgresql/data

volumes:
    book_pgdata: